# Development profile - local PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/golfcomp
    username: ${USER:bmartin}
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
