spring:
  profiles:
    default: dev
  application:
    name: golfcomp
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%10.10t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: INFO
    com.golfcomp: DEBUG
